site_name: CFDTOOLS
repo_name: cfdtools
repo_url: https://github.com/jgressier/cfdtools
edit_uri: ''  #disables edit button

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    #- navigation.tabs

nav:
  - Home: index.md
  - User Guide:
    - command line tools: cli.md
    #- Models: userguide/models.md
    #- Numerical methods: userguide/num.md
  #- Examples: 
    #- Examples: examples.md
    # - Rayleigh flow: examples/nozzle-1-rayleigh.ipynb
    # - Nozzle: examples/nozzle-2-convdiv.ipynb
  - Code reference:
    - internal mesh: cfdtools-format.md
    - IC3 format: IC3-format.md
  - About: 
    - About: about.md
    - Change log: changelog.md

plugins:
  - search
  - include-markdown
  # - mkdocs-jupyter:
  #     execute: True
  #     include_source: False
  - exclude:
      glob:
        - "*.ipynb"
        - "examples/*"
        - "*/*.ipynb"
        - ".ipynb_checkpoints"